# Generated by Django 5.1.3 on 2025-06-16 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_radius', models.FloatField()),
                ('mean_texture', models.FloatField()),
                ('mean_perimeter', models.FloatField()),
                ('mean_area', models.FloatField()),
                ('mean_smoothness', models.FloatField()),
                ('mean_compactness', models.FloatField()),
                ('mean_concavity', models.FloatField()),
                ('mean_concave_points', models.FloatField()),
                ('mean_symmetry', models.FloatField()),
                ('mean_fractal_dimension', models.FloatField()),
                ('radius_error', models.FloatField()),
                ('texture_error', models.FloatField()),
                ('perimeter_error', models.FloatField()),
                ('area_error', models.FloatField()),
                ('smoothness_error', models.FloatField()),
                ('compactness_error', models.FloatField()),
                ('concavity_error', models.FloatField()),
                ('concave_points_error', models.FloatField()),
                ('symmetry_error', models.FloatField()),
                ('fractal_dimension_error', models.FloatField()),
                ('worst_radius', models.FloatField()),
                ('worst_texture', models.FloatField()),
                ('worst_perimeter', models.FloatField()),
                ('worst_area', models.FloatField()),
                ('worst_smoothness', models.FloatField()),
                ('worst_compactness', models.FloatField()),
                ('worst_concavity', models.FloatField()),
                ('worst_concave_points', models.FloatField()),
                ('worst_symmetry', models.FloatField()),
                ('worst_fractal_dimension', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breast_cancer_predictions', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('breast_cancer', 'Breast Cancer'), ('heart_disease', 'Heart Disease'), ('diabetes', 'Diabetes')], max_length=50)),
                ('prediction_data', models.JSONField()),
                ('pdf_generated', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_reports', to='accounts.patient')),
            ],
        ),
    ]
