# Generated by Django 5.1.3 on 2025-06-17 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name'),
        ('predictor', '0002_predictionreport_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverDiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('total_bilirubin', models.FloatField()),
                ('direct_bilirubin', models.FloatField()),
                ('alkaline_phosphotase', models.FloatField()),
                ('alamine_aminotransferase', models.FloatField()),
                ('aspartate_aminotransferase', models.FloatField()),
                ('total_protiens', models.FloatField()),
                ('albumin', models.FloatField()),
                ('albumin_and_globulin_ratio', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liver_disease_predictions', to='accounts.patient')),
            ],
        ),
    ]
