# Generated by Django 5.1.3 on 2025-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseconsultation',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='caseconsultation',
            name='required_specialization',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('General Medicine', 'General Medicine'), ('Surgery', 'Surgery'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology')], max_length=100, null=True),
        ),
    ]
