# Generated by Django 5.1.3 on 2025-06-19 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_chat_session_chat_message_chatimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat_message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='chat_message',
            old_name='has_images',
            new_name='is_processed',
        ),
        migrations.RemoveField(
            model_name='chat_message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chat_message',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='chat_message',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='chat_session',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='chat_session',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chat_message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chat_message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_message',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/'),
        ),
        migrations.AddField(
            model_name='chat_session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('mixed', 'Mixed')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='title',
            field=models.CharField(default='New Chat', max_length=200),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatImage',
        ),
    ]
