# Generated by Django 5.1.3 on 2025-06-19 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_chat_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_message',
            new_name='ChatMessage',
        ),
        migrations.RenameModel(
            old_name='Chat_session',
            new_name='ChatSession',
        ),
    ]
